name:  Mule_Service2_Build_Deploy
on:
  workflow_dispatch:
permissions:
    contents: write
    packages: write
    actions: write
    id-token: write
jobs: 
  Service2_Build:
     name: Mule-Build
     uses: shiyamsundark/DevOpsCommon-Mule/.github/workflows/Build.yml@main
     with:
       Repository: ${{ github.repository }}
