name:  Mule_Service2_Build
on:
  workflow_dispatch:
jobs: 
  Service2_Build:
     name: Mule-Build
     uses: shiyamsundark/DevOpsCommon-Mule/.github/workflows/Build.yml@main
     with:
       Repository: ${{ github.repository }}
