name: Mulesoft - Deploy

on:
  workflow_dispatch:
    inputs:
      MuleEnvironment:
        type: choice
        description: environment
        required: true
        options:
        - Sandbox
        
      version:
        description: REL_Version
        required: true

env:
    
    USERNAME: ${{ secrets.USERNAME }}
    PASSWORD: ${{ secrets.PASSWORD }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
      
   DeploytoMule:
  
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
              java-version: '11'
              distribution: 'adopt'
              
        - name: Version Number
          run: echo "REL_VERSION = ${{ github.event.inputs.version }}"
              
        - name: Downloading the Artifact
          run: wget https://maven.pkg.github.com/shiyamsundark/Customer-service-accounts/com/mycompany/customer-service-accountsv1/${{ github.event.inputs.version }}/customer-service-accountsv1-${{ github.event.inputs.version }}-mule-application.jar 
          env:
            user: shiyamsundark
            password: ${{ secrets.PACKAGEACCESSTOKEN }} 
             
            
        
        
#         - name: Deploying the Artifact to Mule
#           run: mvn deploy -DmuleDeploy 
          
#           mvn package deploy -DmuleDeploy -Dusername= ${{ secrets.USERNAME }} -Dpassword= ${{ secrets.PASSWORD }} -Dworkers=1 -Dworker.type=Micro  -Dmule.version=4.4.0
         
          
