name: Mulesoft - Deploy

on:
  workflow_dispatch:
    inputs:
      MuleEnvironment:
        type: environment
        description: environment
        options:
        - Sandbox
        required: true
      version:
        description: REL_Version
        required: true

env:
    
    USERNAME: ${{ secrets.USERNAME }}
    PASSWORD: ${{ secrets.PASSWORD }}
    
jobs:
      
   DeploytoMule:
  
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
              java-version: '11'
              distribution: 'adopt'
              
        - name: Version Number
          run: echo "REL_VERSION = ${{ github.event.inputs.version }}"
              
        - name: Deploy to Sandbox
        
          run: |
          
             mvn deploy -DmuleDeploy \
             -DnewVersion=${{github.event.inputs.version}} \
             -Denvironment= ${{ github.event.inputs.MuleEnvironment }} \
             -Dmule.artifact=$artifactName \
             -Danypoint.username="$USERNAME" \
             -Danypoint.password="$PASSWORD" \
             -DskipTests
          
#           mvn package deploy -DmuleDeploy -Dusername= ${{ secrets.USERNAME }} -Dpassword= ${{ secrets.PASSWORD }} -Dworkers=1 -Dworker.type=Micro  -Dmule.version=4.4.0
         
          
